In [38]:
import tensorflow as tf
from tensorflow.keras.layers import Conv3D
from tensorflow.keras.models import Model
import os
import numpy as np
from custommodel import  CustomTrainStep

In [39]:
os.environ["CUDA_VISIBLE_DEVICES"] = '7'

In [40]:
x = tf.constant([[1., 1.], [2., 2.]])
tf.reduce_mean(x)

tf.reduce_mean(x, 0)

tf.reduce_mean(x, 1)



<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [26]:
x = np.random.normal(3,5,(2,160,200,160,1))

In [27]:
x = tf.convert_to_tensor(x)

In [28]:
mean = tf.reduce_mean(x)

In [29]:
whitened = x-mean

In [30]:
std = tf.math.reduce_std(x)

In [33]:
tf.math.reduce_std(whitened/std)

<tf.Tensor: shape=(), dtype=float64, numpy=1.0>

In [36]:
tf.reduce_mean(x, axis=(0,1,2))

<tf.Tensor: shape=(160, 1), dtype=float64, numpy=
array([[2.99743772],
       [3.01782469],
       [3.03209182],
       [2.9940234 ],
       [3.03118841],
       [3.00406357],
       [3.00180115],
       [3.00546174],
       [3.01877807],
       [2.97278716],
       [2.97526249],
       [2.98718744],
       [2.99829566],
       [2.98215378],
       [2.97451578],
       [3.0394268 ],
       [3.00134783],
       [2.99521112],
       [3.00014652],
       [3.03621096],
       [3.02079312],
       [3.02682408],
       [3.01119087],
       [3.04574489],
       [2.99311881],
       [3.00518085],
       [2.9810815 ],
       [2.99801098],
       [2.99641796],
       [2.96507973],
       [2.99233363],
       [3.06209557],
       [2.98923748],
       [2.96607836],
       [3.01217569],
       [2.98107988],
       [3.03204064],
       [3.01546145],
       [3.00636718],
       [2.9747157 ],
       [3.00548151],
       [2.96290296],
       [3.00153518],
       [2.99049369],
       [3.00117373],
     

In [73]:
input_shape = (2, 80, 95, 80, 4)
x = tf.random.normal(input_shape)
model = Conv3D(4, 3, activation='relu', input_shape=input_shape[1:])
y = model(x)
kern = model.kernel

In [74]:
eps = 1e-6

In [75]:
mean = tf.reduce_mean(kern, axis=(0,1,2,3), keepdims=True)
std = tf.math.reduce_std(kern, axis=(0,1,2,3), keepdims=True)
std = tf.math.maximum(std, eps)

In [76]:
res = (kern-mean)/(std)

In [77]:
tf.reduce_mean(res)

<tf.Tensor: shape=(), dtype=float32, numpy=-2.2075795e-09>

In [78]:
tf.math.reduce_std(res)

<tf.Tensor: shape=(), dtype=float32, numpy=0.99999994>